[package]
name = "dcpl-parser"
version = "0.1.0"
edition = "2021"

[dependencies]
chumsky = { version = "1.0.0-alpha.8" }
ariadne = "0.4.0"
serde = { version = "1.0.138", features = ["derive"] }
serde_json = "1.0.138"
regex = "1.11.1"
jsonschema = "0.29.0"
